---
title: "Your blog post title"
date: 2019-01-21
---
# title: My First Blog
author: Yash 
email: yash.solanki@rapidops.com
description: > # this means to ignore newlines until "baseurl:"
  This is my First blog.Warm welcome to my blog.

# social links
twitter_username: your-twitter-handle
github_username:  yash-solanki

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

